# Site settings
title: "COMPSCI 682 Neural Networks: A Modern Introduction"
email: compsci682fall19@gmail.com
description: "Course materials and notes for UMass-Amherst COMPSCI 682 Neural Networks: A Modern Introduction."
baseurl: ""
url: "https://compsci682-fa19.github.io/"
github_username:  compsci682-fa19

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
